language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

before_install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpcs --standard=PSR2 src
